### ISSUE TITLE
Pixel Streaming HMD -- Convergence is not working as expected

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure#7]
Originally opened by [@brycelynch ](https://github.com/brycelynch)

When enabling pixel streaming plugin in 5.2 and launching a stream with HMD enabled, the stereo convergence rendered in headset is really distorted and not resolving correctly. Streamer infrastructure is working great (nice job!) and really easy to setup but I'm wondering if there is something not configured correctly for stereo view, or if I've missed something. Tested using Quest Pro.

*On Quest 2 the image converges but the FOV is incorrect.

---

Moved from https://github.com/EpicGames/PixelStreamingInfrastructure/issues/242

**Comment by PhDittmann** [comment]
The message `XREyeView` was introduced in [UE5.4.2](https://github.com/EpicGames/UnrealEngine/commit/e32e1c540b728bd8185c73ed4765d2319fa4e1ba), but is not send in PixelStreamingInfrastructure.

* [WebXRController.ts:159 onXrFrame](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/blob/UE5.4/Frontend/library/src/WebXR/WebXRController.ts#L159)
* https://developer.mozilla.org/en-US/docs/Web/API/XRViewerPose
* https://developer.mozilla.org/en-US/docs/Web/API/XRPose
* https://developer.mozilla.org/en-US/docs/Web/API/XRView

**Comment by PhDittmann** [comment]
I made a [draft](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/compare/master...PhDittmann:PixelStreamingInfrastructure:Feature-Send-XREyeViews), which works at least with Quest 3, but I've a few questions:

* Is an explicit conversion to Float32Array necessary? Because in Firefox + WebXR and Quest 3 the data is already Float32Array. So we do not even need to convert `matrix` to `mat` a few lines above.
* Do we need more detailed checks about `pose.views` and `pose.views[i].eye`?

**Comment by lukehb** [comment]
I am doing some testing with various community members right now, but I think I have a fix in hand. If you'd like to try it all out:

PSInfra
-------------
- Pull the latest Pixel Streaming Infrastructure from `master` branch: https://github.com/EpicGamesExt/PixelStreamingInfrastructure
- You will have to make a self-signed certificate by following this: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/tree/master/SignallingWebServer#self-signed-certificates
- Then run `SignallingWebServer/platform_scripts/cmd/start.bat --https`
- Visit `https://localhost` on your PC to confirm you have this part all set up (note: https - you should see the Pixel Streaming web page after you click the proceed to unsafe page warning).

UE
---------
- Pull the latest UE source code from `ue5-main` branch: https://github.com/EpicGames/UnrealEngine/tree/ue5-main/ (you may have to wait a few hours as my commit has not gone through to Github yet)
- Build the editor from source (sorry this will take a while)
- Make a VR project
- Enable Pixel Streaming plugin
- Disable OpenXR plugin
- Launch your built project with `-pixelstreamingurl=ws://127.0.0.1:8888 -PixelStreamingEnableHMD=true` (and have the signalling server still running)

Headset
-----------
- `ipconfig` to find the local ip address of your machine running UE and signalling server
- In headset browser visit: `https://xxx.xxx.xx.xx` <- your IP here (note the `https`)
- Click the start streaming button
- Click the enter VR button

Would be really good if you can try this out on MQ3 and AVP.

**Comment by PhDittmann** [comment]
Hi @lukehb , thank you for all the work you've done so far!

* User have to use `--https` on very first start / clean state, because having an old SignalingWebServer/config.json will always override it with `false`. The order of CLI and config file was changed in this commit ([src/index.ts:105](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/commit/25379ee859e3d6df1e71ed84144291f0898fed1c#diff-06f3e7fd72091d1341a51e6c180bf900b9e1aaaf3194199d4db3aba8f1b31270R105)).
* #177 works unfortunately only with UE 5.5+
* My experience is, that `ue5-main` is almost never stable. Please reference a commit, we can test I.e. [1f18f428818c5c951021875ebc6c4127e6cf258f](https://github.com/EpicGames/UnrealEngine/commit/1f18f428818c5c951021875ebc6c4127e6cf258f) crashes on startup, because of Vulkan errors. Or we have to wait until UE 5.5 release.

**Comment by lukehb** [comment]
@PhDittmann 

> Please reference a commit, we can test

https://github.com/EpicGames/UnrealEngine/commit/08e45355e45516993c2db887cdd5b72fa20aa805

I would have linked it had it been live on Github (there is like 5hr delay for internal changes to flow into Github). Sorry.

> User have to use --https on very first start / clean state, because having an old SignalingWebServer/config.json will always override it with false

Should be fixed in: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/pull/182

> https://github.com/EpicGamesExt/PixelStreamingInfrastructure/pull/177 works unfortunately only with UE 5.5+

I'll see what I can do about back compat with UE 5.4.2 - I can probably make it stream, just it won't have converged imagery in Meta Quest 3/AVP - but that is better than not working at all. Edit: I have pushed fixes to the `UE5.4` of the PSInfra to restore its XR functionality to match UE 5.4.2, see PR for details: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/pull/187

**Comment by lukehb** [comment]
When https://github.com/EpicGamesExt/PixelStreamingInfrastructure/pull/172/files is paired with https://github.com/EpicGames/UnrealEngine/commit/08e45355e45516993c2db887cdd5b72fa20aa805 stereo imagery is converged on Apple Vision Pro, Meta Quest 2, and Meta Quest 3. Closing!

**Comment by nicklevergne** [comment]
> When https://github.com/EpicGamesExt/PixelStreamingInfrastructure/pull/172/files is paired with [EpicGames/UnrealEngine@08e4535](https://github.com/EpicGames/UnrealEngine/commit/08e45355e45516993c2db887cdd5b72fa20aa805) stereo imagery is converged on Apple Vision Pro, Meta Quest 2, and Meta Quest 3. Closing!

Is there a way I can debug this? I am using UE5.5.1 from the Epic Games Store Library, I am using the default VR project configured correctly per the docs and am using the 5.4 Pixel Streaming. All the right code appears to be there, but I'm still getting this convergence issue on a Quest 3.

**Comment by lukehb** [comment]
Hi @nicklevergne - I just tried using UE 5.5.1 and `UE5.5` branch of this repo on the Meta Quest 3 and stereo imagery appears converged in the headset. Can you confirm the issue reproduces when you use the versions I mentioned?

Note on using the `UE5.4` branch from this repo: it won't have converged imagery, see comment here: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/7#issuecomment-2221961886

> I'll see what I can do about back compat with UE 5.4.2 - I can probably make it stream, just it won't have converged imagery in Meta Quest 3/AVP

**Comment by kwcnldnsldskcls** [comment]
Hello, im using UE5.7.4 PixelStreaming2 on AVP and the connectionn etc is working fine. I have the problem that in VR/XR I can only see like colors. If I look into the sky my rendered video on AVP is blue, if I look down it's brown like it should but I don't see the whole game just like colors. The normal PS for example of the full editor windows works fine. Any idea? thanks in advance!:)
